### ISSUE TITLE
Some question about load-weights

### ISSUE THREAD

**Issue by sakura2233565548** [hulianyuyy/Temporal-Lift-Pooling#2]
I have a question and hope you could answer. Could you load resnet-18 from pre-trained on ImageNet or pre-trained on sign language datasets?

**Comment by hulianyuyy** [comment]
yes, you can find i have loaded the pretrained weight on ImageNet for resnet18 in line 30 in slr_network.py. You can also load the pretrained weight on other sign language datases alternatively.
