### ISSUE TITLE
annotation prefix

### ISSUE THREAD

**Issue by SYQ-s** [hulianyuyy/Temporal-Lift-Pooling#3]
Train.txt and dev.txt are not provided in the CSL dataset on the official website. Are these files generated by yourself? Could you provide the train.txt and dev.txt in dataset_preprocess-CSL.py or inform the text content?
Thank you.

**Comment by hulianyuyy** [comment]
They are provided by the author of the CSL dataset. You can find [train.txt](https://drive.google.com/file/d/1oKsHolNukOhwTiWbG4RT2WBS2FacazE3/view?usp=sharing) and [dev.txt](https://drive.google.com/file/d/1IsGXFyePyNryNefJ8IcVENGvUZmgUa9h/view?usp=sharing) here. Remind to modify the path.
