### ISSUE TITLE
Discrepancy in Learning Rate

### ISSUE THREAD

**Issue by hshreeshail** [hulianyuyy/Temporal-Lift-Pooling#4]
In Section 4.2 of the paper, it is mentioned `initial learning rate 0.001`. However, in `baseline.yaml`, the `base_lr` is `0.0001`. Which is the correct one?

**Comment by hulianyuyy** [comment]
The lr in baseline.yaml is correct. I missed a zero in the paper. Many thanks for your response.



---Original---
From: "Shreeshail ***@***.***&gt;
Date: Wed, Dec 7, 2022 17:26 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [hulianyuyy/Temporal-Lift-Pooling] Discrepancy in Learning Rate(Issue #4)




 
In Section 4.2 of the paper, it is mentioned initial learning rate 0.001. However, in baseline.yaml, the base_lr is 0.0001. Which is the correct one?
