### ISSUE TITLE
Unable to reproduce the training result

### ISSUE THREAD

**Issue by rao1219** [hulianyuyy/Temporal-Lift-Pooling#6]
Hi, 
I use your code and the config but unable to reproduce the expected result, i.e., Dev 19.7 on PHOENIX2014.

I have repeated the same experiment for three times but none of the results are below Dev 21.  

Also, I have ensembled the TLP code in my framework (which is also modified based on VAC), but results show no improvements. 

Would you please help to offer any guidance to reproduce your result? Thanks!

Attached is the training log of one of the repeated experiments.

[TLP.orin.1_dlcha9s04vwqew98-master-0_2023-02-17 13_42_39.txt](https://github.com/hulianyuyy/Temporal-Lift-Pooling/files/10763548/TLP.orin.1_dlcha9s04vwqew98-master-0_2023-02-17.13_42_39.txt)

**Comment by hulianyuyy** [comment]
I have checked the log file you provided but don't find anything wrong. What's the dev results you get upon VAC? Does TLP improve it? I could also provide the log file during training TLP if you need.
